[project]
name = "ilec_pipeline"
version = "0.0.1"
authors = [{ name = "mr.anderson.1725@gmail.com" }]
requires-python = ">=3.11,<3.13"
dependencies = [
    "formulaic==1.2.1",
    "glum==3.2.3",
    # Any dependencies for jobs and pipelines in this project can be added here
    # See also https://docs.databricks.com/dev-tools/bundles/library-dependencies
    #
    # LIMITATION: for pipelines, dependencies are cached during development;
    # add dependencies to the 'environment' section of your pipeline.yml file instead
    "scikit-learn==1.8.0",
    "xgboost==3.2.0",
]

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "databricks-dlt",
    "databricks-connect>=15.4,<15.5",
    "ipykernel",
    "mlflow==3.8.1",
    "databricks-sdk[notebook]>=0.102.0",
    "graphviz==0.21",
    "hatchling>=1.29.0",
]

[project.scripts]
build_lib_wheel = "lib.wheel_task:main"

[tool.hatch.build.targets.wheel]
packages = ["src/model"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120
